version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules

  backend:
    build:
      context: ./student-api
    ports:
      - "1234:1234"
    volumes:
      - ./student-api:/app
      - /app/node_modules
