name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up tags
      run: |
        VERSION="1.${GITHUB_RUN_NUMBER}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

        PROJECT_NAME="mitra"
        echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV

    - name: Build Docker images with docker-compose
      run: |
        docker-compose -p "$PROJECT_NAME" build

    - name: Retag and Push images
      run: |
        FRONTEND_REPO="uros02/mitra88-frontend"
        FRONTEND_IMAGE_ID=$(docker images -q ${PROJECT_NAME}_frontend)

        docker tag $FRONTEND_IMAGE_ID $FRONTEND_REPO:latest
        docker push $FRONTEND_REPO:latest

        docker tag $FRONTEND_IMAGE_ID $FRONTEND_REPO:$VERSION
        docker push $FRONTEND_REPO:$VERSION

        BACKEND_REPO="uros02/mitra88-backend"
        BACKEND_IMAGE_ID=$(docker images -q ${PROJECT_NAME}_backend)

        docker tag $BACKEND_IMAGE_ID $BACKEND_REPO:latest
        docker push $BACKEND_REPO:latest

        docker tag $BACKEND_IMAGE_ID $BACKEND_REPO:$VERSION
        docker push $BACKEND_REPO:$VERSION
