name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_TOKEN}}

    - name: Set up tags
      id: vars
      run: |
        VERSION="1.${GITHUB_RUN_NUMBER}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

        PROJECT_NAME="mitra"
        echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
    
    - name: Build Docker image with docker compose
      run: |
        docker compose -p ${{ env.PROJECT_NAME}} build

    - name: Retag and Push images
      run: |
        PROJECT_NAME="${{ env.PROJECT_NAME}}"

        FRONTEND_REPO="uros02/mitra88-frontend"
        FRONTEND_IMAGE_ID=$(docker images -q --filter reference="${PROJECT_NAME}_frontend" | head -n 1)

        docker tag $FRONTEND_IMAGE_ID $FRONTEND_REPO:latest
        docker push $FRONTEND_REPO:latest

        docker tag $FRONTEND_IMAGE_ID $FRONTEND_REPO:${{ env.VERSION}}
        docker push $FRONTEND_REPO:${{env.VERSION}}

        BACKEND_REPO="uros02/mitra88-backend"
        BACKEND_IMAGE_ID=$(docker images -q --filter reference="${PROJECT_NAME}_backend" | head -n 1)

        docker tag $BACKEND_IMAGE_ID $BACKEND_REPO:latest
        docker push $BACKEND_REPO:lates

        docker tag $BACKEND_IMAGE_ID $BACKEND_REPO:${{ env.VERSION }}
        docker push $BACKEND_REPO:${{ env.VERSION}}

          

      
