name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_TOKEN}}

    - name: Set up tags
      id: vars
      run: |
        VERSION="1.${GITHUB_RUN_NUMBER}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    
    - name: Build Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --tag uros02/mitra88:latest \
          --tag uros02/mitra88:${{ env.VERSION}}

    - name: Push Docker image
      run: |
        docker push uros02/mitra88:latest
        docker push uros02/mitra88:${{ env.VERSION}}

          

      
