name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_TOKEN}}

    - name: Set up tags
      id: vars
      run: |
        VERSION="1.${GITHUB_RUN_NUMBER}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

        PROJECT_NAME="$(basename $PWD)"
        echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
    
    - name: Build Docker image with docker compose
      run: |
        docker compose -p ${{ env.PROJECT_NAME}} build

    - name: Retag and Push images
      run: |
        FRONTEND_LOCAL_IMAGE="${{ env.PROJECT_NAME}}_frontend"
        FRONTEND_REPO="uros02/mitra88"

        docker tag $FRONTEND_LOCAL_IMAGE $FRONTEND_REPO:latest
        docker push $FRONTEND_REPO:latest

        docker tag $FRONTEND_LOCAL_IMAGE $FRONTEND_REPO:${{ env.VERSION}}
        docker push $FRONTEND_REPO:${{ env.VERSION }}

        BACKEND_LOCAL_IMAGE="${{ env.PROJECT_NAME}}_backend"
        BACKEND_REPO="uros02/mitra88-backend"

        docker tag $BACKEND_LOCAL_IMAGE $BACKEND_REPO:latest
        docker push $BACKEND_REPO:latest

        docker tag $BACKEND_LOCAL_IMAGE $BACKEND_REPO:${{ env.VERSION }}
        docker push $BACKEND_REPO:${{ env.VERSION}}

          

      
